#!/bin/bash

WSLSETUPDIR="$PWD/../wsl"

# Install tlp for battery enhancement
sudo apt install -y tlp tlp-rdw
sudo tlp start

# Gnome-tweaks (for system settings)
sudo apt install -y gnome-tweaks

# Install pip
sudo apt install -y python3-pip

# Pandoc
sudo apt install -y pandoc

# Install Latex
echo "latex installations ..."
source ${WSLSETUPDIR}/install-latex.sh

# Install R
echo "R installations ..."
sudo apt install -y r-base-core

# For recompiling C / C++ (especially Rcpp)
echo "ccache installations ..."
sudo apt install -y ccache

# Install nodejs
echo "nodejs installations ..."
source ${WSLSETUPDIR}/install-nvm.sh
source ${WSLSETUPDIR}/install-nodejs.sh  # TODO: change latest_version in this script 

# NOTE: Needs to be run line-by-line
# Install jupyter
echo "You can install jupyter by the following command:"
echo "    source ../wsl/install-jupyter.sh"
# echo "jupyter installations ..."
# source ${WSLSETUPDIR}/install-jupyter.sh

# Install scala
echo "You can install scala by the following command:"
echo "    source ../wsl/install-scala.sh"
# echo "scala installations ..."
# source ${WSLSETUPDIR}/install-scala.sh

# TODO: Install julia from julia website

# Install Audio software
echo "You can install jackd2 by the following command:"
echo "    sudo apt install -y jackd2"
# sudo apt install -y jackd2
