#!/bin/bash


CONFDIR="$PWD/../../conf/unix/"
BINDIR="$PWD/../../bin/unix/"


# Make the following directories if they do not yet exist
mkdir -p ~/bin/
mkdir -p ~/lib/R_lib/
mkdir -p ~/.vim/colors/
mkdir -p ~/.texmf/tex/ # for custom beamer theme
mkdir -p ~/.R/
mkdir -p ~/.ssh/



# Copy these configuration files to the right place
cp ${CONFDIR}/bashrc ~/.bashrc
cp ${CONFDIR}/gitconfig ~/.gitconfig
cp ${CONFDIR}/gitignore_global ~/.gitignore_global
cp ${CONFDIR}/pythonrc ~/.pythonrc
ln -s ${CONFDIR}/redmagick.vim  ~/.vim/colors
cp ${CONFDIR}/R-Makevars ~/.R/Makevars
cp ${CONFDIR}/Renviron ~/.Renviron
cp ${CONFDIR}/Rprofile ~/.Rprofile
cp ${CONFDIR}/ssh_config ~/.ssh/config
cp ${CONFDIR}/tmux.conf ~/.tmux.conf
#cp ${CONFDIR}/vimrc ~/.vim/vimrc
#cp ${CONFDIR}/vimrc.line-feeder-3 ~/.vim/vimrc.line-feeder-3
cp -r ${CONFDIR}/vim/* ~/.vim/
cp ${CONFDIR}/bashColors ~/.bashColors
ln -s ${CONFDIR}/beamerthemealui.sty ~/.texmf/tex/beamerthemealui.sty
ln -s ${CONFDIR}/asaproc.cls ~/.texmf/tex/asaproc.cls


# Copy these scripts to `~/bin`
cp ${BINDIR}/resources ~/bin
ln -s ${BINDIR}/mouse-reset ~/bin
ln -s ${BINDIR}/dirsize ~/bin/dirsize
ln -s ${BINDIR}/vulture.py ~/bin/vulture
ln -s ${BINDIR}/md-include.py ~/bin/md-include
ln -s ${BINDIR}/gush ~/bin/gush
ln -s ${BINDIR}/md ~/bin/md
ln -s ${BINDIR}/sbtgen ~/bin/sbtgen
ln -s ${BINDIR}/sbt-cleanstage ~/bin/sbt-cleanstage
ln -s ${BINDIR}/combineJars ~/bin/combineJars
ln -s ${BINDIR}/mdgen ~/bin/mdgen
ln -s ${BINDIR}/beamergen ~/bin/beamergen
ln -s ${BINDIR}/asamdgen ~/bin/asamdgen
ln -s ${BINDIR}/pdfPage ~/bin/pdfPage
ln -s ${BINDIR}/newH ~/bin/newH
ln -s ${BINDIR}/zipit ~/bin/zipit
ln -s ${BINDIR}/ignoreall ~/bin/ignoreall
ln -s ${BINDIR}/genGitignore ~/bin/genGitignore
ln -s ${BINDIR}/internetSpeedTest ~/bin/internetSpeedTest
### For midi keyboard / synthesizer / midiculous, etc ###
ln -s ${BINDIR}/zyn ~/bin/zyn
ln -s ${BINDIR}/audio-reset ~/bin/audio-reset


# top
# - To configure top to be human-readable, press `E` in top, then
#   to save, hit `W`. 
