#!/bin/bash


CONFDIR="$PWD/../../conf/unix/"
BINDIR="$PWD/../../bin/unix/"


# Make the following directories if they do not yet exist
mkdir -p ~/bin/
mkdir -p ~/lib/R_lib/
mkdir -p ~/.vim/colors/
mkdir -p ~/.texmf-config/tex/ # for custom beamer theme
mkdir -p ~/.R/
mkdir -p ~/.ssh/


# Basic Installations
sudo apt install tmux
sudo apt install vim-gnome
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim


# Copy these configuration files to the right place
cp ${CONFDIR}/bashrc ~/.bashrc
cp ${CONFDIR}/gitconfig ~/.gitconfig
cp ${CONFDIR}/gitignore_global ~/.gitignore_global
cp ${CONFDIR}/pythonrc ~/.pythonrc
ln -s ${CONFDIR}/redmagick.vim  ~/.vim/colors
cp ${CONFDIR}/R-Makevars ~/.R/Makevars
cp ${CONFDIR}/Renviron ~/.Renviron
cp ${CONFDIR}/Rprofile ~/.Rprofile
cp ${CONFDIR}/ssh_config ~/.ssh/config
cp ${CONFDIR}/tmux.conf ~/.tmux.conf
cp ${CONFDIR}/vimrc ~/.vimrc
cp ${CONFDIR}/vimrc.line-feeder-3 ~/.vimrc.line-feeder-3
cp ${CONFDIR}/bashColors ~/.bashColors
ln -s ${CONFDIR}/beamerthemealui.sty ~/.texmf-config/tex/beamerthemealui.sty
ln -s ${BINDIR}/asaproc.cls ~/.texmf-config/tex/asaproc.cls


# Copy these scripts to `~/bin`
cp ${BINDIR}/resources ~/bin
ln -s ${BINDIR}/mouse-reset ~/bin
ln -s ${BINDIR}/dirsize ~/bin/dirsize
ln -s ${BINDIR}/vulture.py ~/bin/vulture
ln -s ${BINDIR}/md-include.py ~/bin/md-include
ln -s ${BINDIR}/gush ~/bin/gush
ln -s ${BINDIR}/md ~/bin/md
ln -s ${BINDIR}/sbtgen ~/bin/sbtgen
ln -s ${BINDIR}/sbt-cleanstage ~/bin/sbt-cleanstage
ln -s ${BINDIR}/combineJars ~/bin/combineJars
ln -s ${BINDIR}/mdgen ~/bin/mdgen
ln -s ${BINDIR}/beamergen ~/bin/beamergen
ln -s ${BINDIR}/asamdgen ~/bin/asamdgen
ln -s ${BINDIR}/pdfPage ~/bin/pdfPage
ln -s ${BINDIR}/newH ~/bin/newH
ln -s ${BINDIR}/zipit ~/bin/zipit
### For midi keyboard / synthesizer / midiculous, etc ###
ln -s ${BINDIR}/zyn ~/bin/zyn
ln -s ${BINDIR}/audio-reset ~/bin/audio-reset



