#!/bin/bash

# Dir containing UNIX binaries and configs 
BINDIR="$PWD/../../bin/unix/"
CONFDIR="$PWD/../../conf/unix/"

# Dir containing MAC-specific binaries and configs 
BINOSXDIR="$PWD/../../bin/osx/"
CONFOSXDIR="$PWD/../../conf/osx/"

# Make a programs dir
mkdir -p ~/programs
mkdir -p ~/.ssh

# Create directories
mkdir -p ~/bin
mkdir -p ~/lib/R_lib
mkdir -p ~/.vim/colors
mkdir -p ~/.R
mkdir -p ~/Library/texmf/tex # for custom beamer theme
mkdir -p ~/.vim/spell
mkdir -p ~/.ssh
touch ~/.pythonhistory

# Copy configuration files
cp ${CONFOSXDIR}/profile ~/.profile
cp ${CONFOSXDIR}/tmux.conf ~/.tmux.conf
cp -r ${CONFDIR}/vim/* ~/.vim/
#cp ${CONFOSXDIR}/vimrc ~/.vimrc
#cp ${CONFDIR}/vimrc.line-feeder-3 ~/.vimrc.line-feeder-3
cp ${CONFDIR}/git-prompt.sh ~/.git-prompt.sh
cp ${CONFDIR}/gitconfig ~/.gitconfig
cp ${CONFDIR}/gitignore_global ~/.gitignore_global
cp ${CONFDIR}/pythonrc ~/.pythonrc
cp ${CONFDIR}/Rprofile ~/.Rprofile
cp ${CONFDIR}/Renviron ~/.Renviron
cp ${BINDIR}/resources ~/bin/resources
cp ${CONFDIR}/ssh_config ~/.ssh/config
ln -s ${CONFDIR}/bashColors ~/.bashColors
ln -s ${CONFDIR}/asaproc.cls ~/Library/texmf/tex/asaproc.cls
ln -s ${CONFDIR}/beamerthemealui.sty ~/Library/texmf/tex/beamerthemealui.sty
ln -s ${CONFDIR}/redmagick.vim ~/.vim/colors/redmagick.vim

# Copy scripts
ln -s ${BINDIR}/vulture.py ~/bin/vulture
ln -s ${BINDIR}/dirsize ~/bin/dirsize
ln -s ${BINDIR}/gush ~/bin/gush
ln -s ${BINDIR}/md ~/bin/md
ln -s ${BINDIR}/sbtgen ~/bin/sbtgen
ln -s ${BINDIR}/sbt-cleanstage ~/bin/sbt-cleanstage
ln -s ${BINDIR}/combineJars ~/bin/combineJars
ln -s ${BINDIR}/mdgen ~/bin/mdgen
ln -s ${BINDIR}/beamergen ~/bin/beamergen
ln -s ${BINDIR}/asamdgen ~/bin/asamdgen
ln -s ${BINDIR}/ignoreall ~/bin/ignoreall


# Install Basic Programs
## Install brew
git clone https://github.com/mxcl/homebrew.git ~/programs

# Install Vundle
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

## Install gnu-sed for gush
## If gnu-sed is previously installed,
## brew uninstall gnu-sed
brew install gnu-sed --with-default-names

## Install TMUX
## Note in osx, to change pane size: Ctrl-b (release) + Option + Arrow
brew install tmux 

## Install this so that `open` can be used in tmux
brew install reattach-to-user-namespace
brew upgrade reattach-to-user-namespace

## Install vim for mac
brew install MacVim

