#!/bin/bash

# Apperance
export CLICOLOR=1

# Comment if not using redmagick
export TERM=xterm-256color

export LSCOLORS=ExFxBxDxCxegedabagacad
alias ls='ls -GFh'

# Interactive commands for not overwriting files
alias mv="/bin/mv -i"
alias cp="/bin/cp -i"
alias rm="/bin/rm -i"

# Alias
alias dir="ls -hla"
alias taro="tar -zxf"
alias tma="tmux attach -t"
alias vi="nvim"

# Set-up prompt
PS1="\h:\W$ "

# Git prompt
source ~/.git-prompt.sh

# Default Editor
export EDITOR=nvim

# Search Paths
export PATH=~/bin:$PATH
export PATH=$HOME/programs/homebrew/bin:$PATH
export PYTHONSTARTUP=~/.pythonrc

# MacVim
# alias vi="mvim -v"
# alias vim="mvim -v"

# Makefile completion.
complete -W "\`grep -oE '^[a-zA-Z0-9_.-]+:([^=]|$)' ?akefile | sed 's/[^a-zA-Z0-9_.-]*$//'\`" make
