SHELL := /bin/bash

linux-server:
	cd os/linux-server && bash setup.sh && bash install.sh

osx:
	cd os/osx && bash setup.sh && bash install.sh

ubuntu:
	cd os/ubuntu && bash setup.sh && bash install.sh

wsl: ubuntu
