# switch panes using hlkj
unbind-key l
bind-key h select-pane -L
bind-key l select-pane -R
bind-key k select-pane -U
bind-key j select-pane -D
unbind-key Left
unbind-key Right
unbind-key Up
unbind-key Down

# Colors in tmux.
set -g default-terminal "screen-256color"

### ALL THE OTHER STUFF.
# NOTE: This is the updated tmux.conf for tmux v2.9+.
# Most of the style options won't work for tmux < v2.9.
# See: https://github.com/tmux/tmux/wiki/FAQ#how-do-i-translate--fg--bg-and--attr-options-into--style-options
# See: https://github.com/tmux/tmux/issues/1689

# Statusbar.
set -g status-style fg=colour194,bg=colour238
set -g status-right "#h | %e %B %Y | %H:%M "

# Tmux command prompt.
set -g message-style fg=colour238,bg=colour194

# Pane colors.
set -g pane-border-style fg=colour238
set -g pane-active-border-style fg=colour210

# Reorder windows when one is closed
set-option -g renumber-windows on

# Window splitting in same dir. Done by default in prior to v1.9.
# NOTE: Comment out for tmux < v1.9.
bind-key c new-window -c "#{pane_current_path}"
bind-key % split-window -h -c "#{pane_current_path}"
bind-key '"' split-window -v -c "#{pane_current_path}"

# Mouse mode for tmux. 
# NOTE: Comment out for tmux < v2.4.
set-option -g mouse on

# Auto renumber windows
set-option -g renumber-windows on

# Keybinds for window swapping.
bind-key -n C-S-Left swap-window -t -1\; select-window -t -1
bind-key -n C-S-Right swap-window -t +1\; select-window -t +1

# Screen refreshing.
bind-key -n F1 refresh-client
